### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yoheioda0127** [yoheioda0127/furima-29606#9]
・自身のフリマアプリのURL 
    https://furima-29606.herokuapp.com/

・Basic認証のIDとパスワード |  
    maikemi00romans@gmail.com
    a<025987

・出品者用のメールアドレス/パスワード&購入者用のメールアドレスとパスワード(※全てのユーザーが商品出品中)

　①ようへい　maikemi@gamil.com    a025987
　②おじさん　ojisan@gmail.com        a025987
　③山田太郎　taro@gamil.com           a025987

・購入用カードの番号・期限・セキュリティコード
    4242424242424242 ・333・ 3月33年

以上です。よろしくお願いいたします。よろしくお願いいたします。

**Comment by yoheioda0127** [comment]
失礼いたしました。
一部修正です。

・購入用カードの番号・期限・セキュリティコード
4242424242424242・ 3月33年・123

**Comment by kohei-ito** [comment]
yoheioda0127 さん、ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
BASIC認証が実装されていないので、実装する。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yoheioda0127** [comment]
・自身のフリマアプリのURL
https://furima-29606.herokuapp.com/

・Basic認証のID・パスワード |  
　　　furima　　・　4242

・出品者用のメールアドレス/パスワード&購入者用のメールアドレスとパスワード(※全てのユーザーが商品出品中)

　①ようへい　maikemi@gamil.com a025987
　②おじさん　ojisan@gmail.com a025987
　③山田太郎　taro@gamil.com a025987

・購入用カードの番号・期限・セキュリティコード
4242424242424242・ 3月33年 ・123

**Comment by kohei-ito** [comment]
yoheioda0127 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できましたので、　**LGTMとさせていただきます！** ✨　
おめでとうございます！🎉

技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております！

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by yoheioda0127** [comment]
ありがとうございました。
